version: "3.8"


services:
    #nginx
    server:
        # image: 'nginx:stable-alpine'
        container_name: nginx
        build:
            context: .
            dockerfile: ./dockerfiles-dev/nginx/nginx.dockerfile
        ports:
            - '8000:8000'
        volumes:
            - .:/var/www/html
            - ./docker-dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql

    #php
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./dockerfiles-dev/php/php.dockerfile
        volumes:
            - .:/var/www/html:delegated

    #mysql
    mysql:
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        image: 'mysql:5.7'
        env_file:
            - ./dockerfiles-dev/env/mysql.env
        volumes:
            - .:/var/www/html

    #composer
    composer:
        container_name: composer
        build:
            context: ./dockerfiles-dev
            dockerfile: ./composer/composer.dockerfile
        volumes:
            - .:/var/www/html

    #artisan
    artisan:
        container_name: artisan
        build:
            context: .
            dockerfile: ./dockerfiles-dev/php/php.dockerfile
        volumes:
            - .:/var/www/html
        entrypoint: ['php', '/var/www/html/artisan']

    #redis
    redis:
        container_name: redis
        image: redis:alpine
        volumes:
            - .:/var/www/html


    supervisor:
        container_name: supervisor
        build:
            context: .
            dockerfile: ./dockerfiles-dev/supervisor/supervisor.dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - php
            - mysql
            - redis


    #phpmyadmin
    phpmyadmin:
        container_name: phpmyadmin
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - 8001:80
